## Tensor Datatypes (Attributes)
**Note**: Tesnor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning
1. Tensors are not the right **datatype**
2. Tensors are not the right **shape**
3. Tensors are not on the right **device**


In [9]:
import torch
import numpy as np
import pandas as pd

In [13]:
int_16_tensor = torch.tensor([1, 2, 3, 4, 5],
                             dtype=torch.int16)

float_16_tensor = torch.tensor([1, 2, 3, 4, 5],
                                 dtype=torch.float16)

int_16_tensor * float_16_tensor

tensor([ 1.,  4.,  9., 16., 25.], dtype=torch.float16)

## Getting Information from Tensors
1. Tensors are not the right **datatype** - to get datatype from a tensor, use tensor.dtype
2. Tensors are not the right **shape** to get shape from a tensor, use tensor.shape
3. Tensors are not on the right **device** to get the device from a tensor, use tensor.device

In [25]:
rand_tensor = rand_tensor = torch.rand([5, 5],
                                       dtype=torch.float16
                                       )
rand_tensor

tensor([[0.9370, 0.5981, 0.5024, 0.6538, 0.2505],
        [0.3999, 0.4102, 0.8037, 0.3760, 0.0562],
        [0.6221, 0.0479, 0.1904, 0.2783, 0.8359],
        [0.7104, 0.6895, 0.4888, 0.2729, 0.2354],
        [0.3198, 0.8813, 0.5635, 0.9370, 0.7720]], dtype=torch.float16)

In [26]:
# Find out some data from a tensor
print(rand_tensor)
print(rand_tensor.shape)
print(rand_tensor.dtype)
print(rand_tensor.device)

tensor([[0.9370, 0.5981, 0.5024, 0.6538, 0.2505],
        [0.3999, 0.4102, 0.8037, 0.3760, 0.0562],
        [0.6221, 0.0479, 0.1904, 0.2783, 0.8359],
        [0.7104, 0.6895, 0.4888, 0.2729, 0.2354],
        [0.3198, 0.8813, 0.5635, 0.9370, 0.7720]], dtype=torch.float16)
torch.Size([5, 5])
torch.float16
cpu


## Manipulating Tensors
Tensor operation include:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [28]:
# Addition

from torch import tensor


add_tensor = torch.tensor([1, 2, 3, 4, 5])
print(add_tensor + 20)
print(add_tensor)

tensor([21, 22, 23, 24, 25])
tensor([1, 2, 3, 4, 5])


In [31]:
# Multiplication
mul_tensor = torch.tensor([1, 2, 3, 4, 5])
mul_tensor *= 10
mul_tensor

tensor([10, 20, 30, 40, 50])

In [32]:
# Subraction
sub_tensor = torch.tensor([1, 2, 3, 4, 5])
sub_tensor -= 10
sub_tensor

tensor([-9, -8, -7, -6, -5])

In [33]:
# Try out pytorch inbuilt functions
torch.mul(add_tensor, 10)

tensor([10, 20, 30, 40, 50])

## Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise
2. Matrix Multiplication (dot-product)


In [34]:
print(add_tensor, "*", add_tensor)
torch.mul(add_tensor, add_tensor)

tensor([1, 2, 3, 4, 5]) * tensor([1, 2, 3, 4, 5])


tensor([ 1,  4,  9, 16, 25])