## Tensor Data types (Attributes)
**Note**: Tensor data types is one of the 3 big errors you'll run into with Pytorch & deep learning
1. Tensors are not the right **datatype**
2. Tensors are not the right **shape**
3. Tensors are not on the right **device**


In [11]:
import torch
import numpy as np
import pandas as pd

In [12]:
int_16_tensor = torch.tensor([1, 2, 3, 4, 5],
                             dtype=torch.int16)

float_16_tensor = torch.tensor([1, 2, 3, 4, 5],
                                 dtype=torch.float16)

int_16_tensor * float_16_tensor

tensor([ 1.,  4.,  9., 16., 25.], dtype=torch.float16)

## Getting Information from Tensors
1. Tensors are not the right **datatype** - to get datatype from a tensor, use tensor.dtype
2. Tensors are not the right **shape** to get shape from a tensor, use tensor.shape
3. Tensors are not on the right **device** to get the device from a tensor, use tensor.device

In [13]:
rand_tensor = rand_tensor = torch.rand([5, 5],
                                       dtype=torch.float16
                                       )
rand_tensor

tensor([[0.1582, 0.6895, 0.3989, 0.9146, 0.7212],
        [0.7266, 0.8242, 0.0562, 0.2134, 0.7822],
        [0.5078, 0.9985, 0.6650, 0.3745, 0.4893],
        [0.2568, 0.6753, 0.8589, 0.4648, 0.5972],
        [0.5649, 0.0337, 0.6328, 0.8418, 0.3823]], dtype=torch.float16)

In [14]:
# Find out some data from a tensor
print(rand_tensor)
print(rand_tensor.shape)
print(rand_tensor.dtype)
print(rand_tensor.device)

tensor([[0.1582, 0.6895, 0.3989, 0.9146, 0.7212],
        [0.7266, 0.8242, 0.0562, 0.2134, 0.7822],
        [0.5078, 0.9985, 0.6650, 0.3745, 0.4893],
        [0.2568, 0.6753, 0.8589, 0.4648, 0.5972],
        [0.5649, 0.0337, 0.6328, 0.8418, 0.3823]], dtype=torch.float16)
torch.Size([5, 5])
torch.float16
cpu


## Manipulating Tensors
Tensor operation include:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [15]:
# Addition

from torch import tensor


add_tensor = torch.tensor([1, 2, 3, 4, 5])
print(add_tensor + 20)
print(add_tensor)

tensor([21, 22, 23, 24, 25])
tensor([1, 2, 3, 4, 5])


In [16]:
# Multiplication
mul_tensor = torch.tensor([1, 2, 3, 4, 5])
mul_tensor *= 10
mul_tensor

tensor([10, 20, 30, 40, 50])

In [17]:
# Subtraction
sub_tensor = torch.tensor([1, 2, 3, 4, 5])
sub_tensor -= 10
sub_tensor

tensor([-9, -8, -7, -6, -5])

In [18]:
# Try out pytorch inbuilt functions
torch.mul(add_tensor, 10)

tensor([10, 20, 30, 40, 50])

## Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise
2. Matrix Multiplication (dot-product)

There are two main rules when performing matrix multiplication:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work!
* `(3,2) @ (2,3)` will work!

2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` resulting shape is 2x2
* `(3,2) @ (2,3)` resulting shape is 3x3




In [19]:
print(add_tensor, "*", add_tensor)
torch.mul(add_tensor, add_tensor)

tensor([1, 2, 3, 4, 5]) * tensor([1, 2, 3, 4, 5])


tensor([ 1,  4,  9, 16, 25])

#### One of the most common areas in deep learning: shape errors

In [20]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix the tensor shape issues, we can manipulate the shape of one of the tensors using a transpose
A **transpose** switch the axes or dimensions of a given tensor


In [21]:
tensor_b.T
tensor_b.T.shape

torch.Size([2, 3])

In [22]:
# The matrix multiplication works when tensor_b is transposed

torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [23]:
print(f'Original shape: tensor_a: {tensor_a.shape}, tensor_b: {tensor_b.shape}')
print(f'After transpose: tensor_a: {tensor_a.shape} (still the same shape), tensor_b: {tensor_b.T.shape}')
print(f'Multiplying the tensors: {tensor_a.shape} inner dimensions must match {tensor_b.T.shape}') 
print('Output: \n')
output = torch.mm(tensor_a, tensor_b.T)
print(output)
print(f'\nShape of output: {output.shape}')

Original shape: tensor_a: torch.Size([3, 2]), tensor_b: torch.Size([3, 2])
After transpose: tensor_a: torch.Size([3, 2]) (still the same shape), tensor_b: torch.Size([2, 3])
Multiplying the tensors: torch.Size([3, 2]) inner dimensions must match torch.Size([2, 3])
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Shape of output: torch.Size([3, 3])


In [24]:
####### Transposing tensor a instead of tensor b
output2 = torch.mm(tensor_a.T, tensor_b)

print(output2)

tensor([[ 76, 103],
        [100, 136]])


### Finding the min, max, mean, sum, etc (tensor aggregation)


In [25]:
# Create a tensor
x = torch.arange(0, 101, 10)
x


tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [26]:
# Find the minimum value
torch.min(x), x.min()

(tensor(0), tensor(0))

In [27]:
# Find the maximum value
torch.max(x), x.max()

(tensor(100), tensor(100))

In [28]:
# Find the mean
torch.mean(x)

### ^^^ Got the dtype error because the tensor was of type int64


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [29]:
# Change the dtype to float ---> torch.mean(x.float()) requires the tensor to be float32 to work
torch.mean(x.float()), x.float().mean()

(tensor(50.), tensor(50.))

In [30]:
torch.sum(x), x.sum()

(tensor(550), tensor(550))

### Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze - removes a `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


Manipulate our tensors in someway to change their shape

In [31]:
# Create a new tensor
y = torch.arange(0, 9)
y, y.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]))

In [32]:
#Add an extra dimension

# Has to be compatible with the tensor size i.e 3x3 = 9, 9x1 = 9
y_reshaped = y.reshape(3, 3)
y_reshaped, y_reshaped.shape

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 torch.Size([3, 3]))

In [33]:
z = y.view(1, 9)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 9]))

In [34]:
# Changing z change y because a view of a tensor share the same memory as the original tensor
z[:, 0] = 5
z, y

(tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8]]), tensor([5, 1, 2, 3, 4, 5, 6, 7, 8]))

In [35]:
# Stack tensors on top of each other
y_stacked = torch.stack([y, y,y,y,y,y,y]
                        , dim=0)
y_stacked

tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8]])

In [36]:
y_reshaped = y.reshape(1, 9)
y_reshaped.shape

torch.Size([1, 9])

In [38]:
y_reshaped.squeeze().shape

torch.Size([9])

In [45]:
# Remove the extra dimension
y_reshaped = y_reshaped.squeeze()
print(f'\nNew Tensor: \n {y_reshaped}')
print(f'\nShape of new tensor: {y_reshaped.shape}')


### Unsqueeze a tensor - add a dimension
y_unsqueeze = y_reshaped.unsqueeze(dim=0)
print(f'\nNew Tensor: \n {y_unsqueeze}')
print(f'\nShape of new tensor: {y_unsqueeze.shape}')




New Tensor: 
 tensor([5, 1, 2, 3, 4, 5, 6, 7, 8])

Shape of new tensor: torch.Size([9])

New Tensor: 
 tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8]])

Shape of new tensor: torch.Size([1, 9])


In [48]:
## torch.permute() - rearrange the dimensions of a tensor ##
## See this a lot with image recognition ##
## The dimensions are usually (channels, height, width) ##
x_original = torch.rand(size=(3, 224, 224)) # 3 color channels (RGB), 224 height, 224 width


#Permute the tensor
x_permuted = x_original.permute(1, 2, 0)


print(f'Original shape: {x_original.shape}')
print(f'Permuted shape: {x_permuted.shape}')

Original shape: torch.Size([3, 224, 224])
Permuted shape: torch.Size([224, 224, 3])


In [50]:
x_original [0, 0, 0] = 23413

In [51]:
x_permuted[0, 0, 0]

tensor(23413.)

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [1]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Index on our new tensor
x[0]


# Let's Index on the middle bracket
x[0, 1]


# Let's index on the most inner bracket
x[0,2,2]

tensor(9)

In [3]:
# You can also use the : to select all of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [5]:
# Get all values of 0th and 1st dimension but only the first two values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [8]:
# Index on x to return 9
x[0,2,2]


# Index on x to return 3,6,9
x[0,:,2]

tensor(9)

### PyTorch tensors & Numpy
NuPy is a popular scientific Python numerical computing Library

Pytorch has functionality to interact with it

Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

PyTorch tensor -> NumPy -> `torch.tensor.numpy`

In [16]:
# Numpy array to tensor
import array
import torch
import numpy as np

array = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
tensor = torch.from_numpy(array).type(torch.float32) # When converting from numpy to a tensor, the data is defaulted to float64

print(f'Numpy array: {array}')
print(f'Torch tensor: {tensor}')

Numpy array: [1. 2. 3. 4. 5.]
Torch tensor: tensor([1., 2., 3., 4., 5.])


In [19]:

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [20]:
# Change the tensor what will happen to the numpy tensor?
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

### Reproducibility (trying to take the random out of randomness)

In short how a neural network works and learns:

start with random number --> tensor operations --> update random numbers to make them better at representations of the data --> again --> again --> and again...

To reduce the randomness in neural networks and PyTorch comes the concept of a `random seed`

In [21]:
import random
import torch


# Create two random tensors
random_tensor_a = torch.rand(5, 3) 
random_tensor_b = torch.rand(5, 3)


# Are they equal?
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[5.3064e-01, 4.4200e-01, 5.9391e-01],
        [5.1664e-02, 4.1238e-01, 9.5685e-01],
        [5.0082e-03, 4.9574e-01, 5.2136e-01],
        [7.3719e-04, 3.2414e-01, 4.7927e-01],
        [3.5666e-01, 3.3860e-01, 6.3354e-02]])
tensor([[0.7290, 0.0689, 0.5403],
        [0.3625, 0.9602, 0.7950],
        [0.4766, 0.4210, 0.7801],
        [0.0151, 0.4709, 0.5948],
        [0.8992, 0.8977, 0.1400]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])
