## Tensor Datatypes (Attributes)
**Note**: Tesnor datatypes is one of the 3 big errors you'll run into with Pytorch & deep learning
1. Tensors are not the right **datatype**
2. Tensors are not the right **shape**
3. Tensors are not on the right **device**


In [2]:
import torch
import numpy as np
import pandas as pd

In [3]:
int_16_tensor = torch.tensor([1, 2, 3, 4, 5],
                             dtype=torch.int16)

float_16_tensor = torch.tensor([1, 2, 3, 4, 5],
                                 dtype=torch.float16)

int_16_tensor * float_16_tensor

tensor([ 1.,  4.,  9., 16., 25.], dtype=torch.float16)

## Getting Information from Tensors
1. Tensors are not the right **datatype** - to get datatype from a tensor, use tensor.dtype
2. Tensors are not the right **shape** to get shape from a tensor, use tensor.shape
3. Tensors are not on the right **device** to get the device from a tensor, use tensor.device

In [4]:
rand_tensor = rand_tensor = torch.rand([5, 5],
                                       dtype=torch.float16
                                       )
rand_tensor

tensor([[0.9277, 0.6797, 0.1494, 0.5503, 0.0186],
        [0.5225, 0.0625, 0.4756, 0.0894, 0.7207],
        [0.5283, 0.3896, 0.8398, 0.7471, 0.0293],
        [0.2124, 0.6875, 0.1421, 0.4385, 0.3257],
        [0.3882, 0.6699, 0.3384, 0.8545, 0.0215]], dtype=torch.float16)

In [5]:
# Find out some data from a tensor
print(rand_tensor)
print(rand_tensor.shape)
print(rand_tensor.dtype)
print(rand_tensor.device)

tensor([[0.9277, 0.6797, 0.1494, 0.5503, 0.0186],
        [0.5225, 0.0625, 0.4756, 0.0894, 0.7207],
        [0.5283, 0.3896, 0.8398, 0.7471, 0.0293],
        [0.2124, 0.6875, 0.1421, 0.4385, 0.3257],
        [0.3882, 0.6699, 0.3384, 0.8545, 0.0215]], dtype=torch.float16)
torch.Size([5, 5])
torch.float16
cpu


## Manipulating Tensors
Tensor operation include:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [6]:
# Addition

from torch import tensor


add_tensor = torch.tensor([1, 2, 3, 4, 5])
print(add_tensor + 20)
print(add_tensor)

tensor([21, 22, 23, 24, 25])
tensor([1, 2, 3, 4, 5])


In [7]:
# Multiplication
mul_tensor = torch.tensor([1, 2, 3, 4, 5])
mul_tensor *= 10
mul_tensor

tensor([10, 20, 30, 40, 50])

In [8]:
# Subraction
sub_tensor = torch.tensor([1, 2, 3, 4, 5])
sub_tensor -= 10
sub_tensor

tensor([-9, -8, -7, -6, -5])

In [9]:
# Try out pytorch inbuilt functions
torch.mul(add_tensor, 10)

tensor([10, 20, 30, 40, 50])

## Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise
2. Matrix Multiplication (dot-product)

There are two main rules when performing matrix multiplication:
1. The **inner dimesions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work!
* `(3,2) @ (2,3)` will work!

2. The resulting matrix has the shape of the **outer dimensions**
* `(2,3) @ (3,2)` resulting shape is 2x2
* `(3,2) @ (2,3)` resulting shape is 3x3




In [10]:
print(add_tensor, "*", add_tensor)
torch.mul(add_tensor, add_tensor)

tensor([1, 2, 3, 4, 5]) * tensor([1, 2, 3, 4, 5])


tensor([ 1,  4,  9, 16, 25])

#### One of the most common areas in deeplearning: shape errors

In [11]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

torch.mm(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix the tensor shape issues, we can maniupluate the shape of one of the tensors using a transpose
A **transpose** switch the axes or dimesions of a given tensor


In [13]:
tensor_b.T
tensor_b.T.shape

torch.Size([2, 3])

In [14]:
# The matrix multiplication works when tensor_b is transposed

torch.mm(tensor_a, tensor_b.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [16]:
print(f'Original shape: tensor_a: {tensor_a.shape}, tensor_b: {tensor_b.shape}')
print(f'After transpose: tensor_a: {tensor_a.shape} (still the same shape), tensor_b: {tensor_b.T.shape}')
print(f'Multiplying the tensors: {tensor_a.shape} inner dimensions must match {tensor_b.T.shape}') 
print('Output: \n')
output = torch.mm(tensor_a, tensor_b.T)
print(output)
print(f'\nShape of output: {output.shape}')

Original shape: tensor_a: torch.Size([3, 2]), tensor_b: torch.Size([3, 2])
After transpose: tensor_a: torch.Size([3, 2]) (still the same shape), tensor_b: torch.Size([2, 3])
Multiplying the tensors: torch.Size([3, 2]) inner dimensions must match torch.Size([2, 3])
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Shape of output: torch.Size([3, 3])


In [18]:
####### Transposing tensor a instead of thesor b
output2 = torch.mm(tensor_a.T, tensor_b)

print(output2)

tensor([[ 76, 103],
        [100, 136]])


### Finding the min, max, mean, sum, etc (tensor aggreagtion)


In [21]:
# Create a tensor
x = torch.arange(0, 101, 10)
x


tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [22]:
# Find the mibnimum value
torch.min(x), x.min()

(tensor(0), tensor(0))

In [23]:
# Find the maximum value
torch.max(x), x.max()

(tensor(100), tensor(100))

In [25]:
# Find the mean
torch.mean(x)

### ^^^ Got the dtype error because the tensor was of type int64


RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [27]:
# Change the dtype to float ---> torch.mean(x.float()) requires the tensor to be float32 to work
torch.mean(x.float()), x.float().mean()

(tensor(50.), tensor(50.))

In [28]:
torch.sum(x), x.sum()

(tensor(550), tensor(550))

### Reshaping, stacking, squeezing, and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memor as the original tensor
* Stacking - combine multiple tensors on top of each other or side by side
* Squeeze - removes a `1` dimesions from a tensor
* Unsqueeze - add a `1` dimesion to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


Manipulate our tensors in someway to change their shape

In [29]:
# Create a new tensor
y = torch.arange(0, 9)
y, y.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([9]))

In [31]:
#Add an extra dimension

# Has to be compatible with the tensor size i.e 3x3 = 9, 9x1 = 9
y_reshaped = y.reshape(3, 3)
y_reshaped, y_reshaped.shape

(tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]),
 torch.Size([3, 3]))

In [32]:
z = y.view(1, 9)
z, z.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]]), torch.Size([1, 9]))

In [33]:
# Changing z change y because a view of a tensor share the same memory as the original tensor
z[:, 0] = 5
z, y

(tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8]]), tensor([5, 1, 2, 3, 4, 5, 6, 7, 8]))

In [37]:
# Stack tensors on top of each other
y_stacked = torch.stack([y, y,y,y,y,y,y]
                        , dim=0)
y_stacked

tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8],
        [5, 1, 2, 3, 4, 5, 6, 7, 8]])