<a href="https://colab.research.google.com/github/JakeVerry/Learn_Pytorch/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor Data types (Attributes)
**Note**: Tensor data types is one of the 3 big errors you'll run into with Pytorch & deep learning
1. Tensors are not the right **datatype**
2. Tensors are not the right **shape**
3. Tensors are not on the right **device**

In [2]:
import torch
import numpy as np
import pandas as pd

## Putting tensors on GPUs
the reason we want GPUs is because it processes data faster

In [3]:
# Create a tensor (default on the CPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor = torch.tensor([1,2,3])

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [4]:
# Move tensor to GPU if available:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [3]:
# Create a random tensor with shape (7,7)
import torch
import numpy as np

tensor = torch.rand(7,7)
tensor2 = torch.rand(1,7)

In [6]:
# Perform a matrix multiplication between the two tensors
import torch

#Set the seed to 0

torch.manual_seed(0)

#Generate two random tensors of shape (5,5) and (5,1)

tensor1 = torch.rand(5,5)

tensor21 = torch.rand(5,1)

tensor1.mm(tensor21)

tensor([[1.1488],
        [1.1704],
        [0.7175],
        [1.1156],
        [1.5817]])

In [7]:
print(tensor21.device)

cpu
